FROM python:3.10-bullseye
RUN useradd -M -d /nonexistent app && pip install async-timeout==4.0.2 bcrypt==3.2.2 bidict==0.22.0 certifi==2021.10.8 cffi==1.15.0 charset-normalizer==2.0.12 click==8.1.0 cryptography==37.0.2 deprecated==1.2.13 flask==2.1.0 flask-login==0.5.0 flask-socketio==5.1.1 flask-wtf==1.0.0 gevent==21.12.0 gevent-websocket==0.10.1 greenlet==1.1.2 gunicorn==20.1.0 idna==3.3 importlib-metadata==4.11.3 itsdangerous==2.1.2 jinja2==3.1.1 lxml==4.8.0 markupsafe==2.1.1 packaging==21.3 paramiko==2.11.0 pycparser==2.21 pynacl==1.5.0 pyparsing==3.0.9 pysftp==0.2.9 python-dateutil==2.8.2 python-engineio==4.3.1 python-socketio==5.5.2 redis==4.3.1 requests==2.27.1 rq==1.10.1 schedule==1.1.0 six==1.16.0 urllib3==1.26.9 werkzeug==2.0.3 wheel==0.37.1 wrapt==1.14.1 wtforms==3.0.1 zipp==3.7.0 zope-event==4.5.0 zope-interface==5.4.0 zxcvbn==4.4.28 && mkdir /app && mkdir /app/instance && chown app:app /app/instance
COPY app /app/app
        COPY scripts /app/scripts
USER app
WORKDIR /app
EXPOSE 5000
        CMD gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:5000 'app:create_app()'
