version: "3.9"
services:
  webapp:
    image: jototland/phonelog:1.0.0
    volumes:
      - "phonelog_data:/app/instance"
    expose:
      - "5000"
    environment:
      - TRUSTED_PROXIES_COUNT=1
      - REDIS_HOST=redis
    env_file:
      - secrets/secret_key.env
  rq_worker:
    image: jototland/phonelog:1.0.0
    command: ./scripts/start-rq.sh
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST=redis
      - INTERNAL_URL=http://webapp:5000/
    volumes:
      - "phonelog_data:/app/instance"
    env_file:
      - secrets/secret_key.env
      - secrets/zisson_credentials.env # SECRET_KEY, ZISSON_API_USERNAME, ZISSON_API_PASSWORD
  scheduler:
    image: jototland/phonelog:1.0.0
    command: python -m app.scheduler
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST=redis
    volumes:
      - "phonelog_data:/app/instance"
    env_file:
      - secrets/secret_key.env
  caddy:
    image: caddy:2-alpine
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy_data:/data"
      - "caddy_config:/config"
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
  redis:
    image: redis:7-alpine
    command: redis-server
    expose:
      - "6379"
volumes:
  phonelog_data:
  caddy_data:
  caddy_config:
