version: "3.9"
services:
  phonelog:
    image: jototland/phonelog
    volumes:
      - "phonelog_data:/app/instance"
    expose:
      - "5000"
    environment:
      - TRUSTED_PROXIES_COUNT=1
      - REDIS_HOST=redis
    env_file:
      - secrets.txt # SECRET_KEY, ZISSON_API_USERNAME, ZISSON_API_PASSWORD
  rq_worker:
    image: jototland/phonelog
    command: ./start-rq.sh
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST=redis
    volumes:
      - "phonelog_data:/app/instance"
    env_file:
      - secrets.txt # SECRET_KEY, ZISSON_API_USERNAME, ZISSON_API_PASSWORD
  scheduler:
    image: jototland/phonelog
    command: python app/scheduler.py
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST=redis
    volumes:
      - "phonelog_data:/app/instance"
    env_file:
      - secrets.txt # SECRET_KEY, ZISSON_API_USERNAME, ZISSON_API_PASSWORD
  caddy:
    image: caddy:2-alpine
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy_data:/data"
      - "caddy_config:/config"
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
  redis:
    image: redis:7-alpine
    expose:
      - "6379"
volumes:
  phonelog_data:
  caddy_data:
  caddy_config:
